name: Linting and code formatting

on:
  push:


jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: ctions/setup-python@v5
        with:
          python-version: 3.8.10
      - name: Get cache
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      # Install packages
      - name: Install packages required for installation
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: pip install -r requirements.txt black isort

      # Format code
      - name: Format with Black
        run: python -m black .
      - name: Sort imports with isort
        run: python -m isort .
