name: Linting and code formatting

on:
  push:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      # Install dependencies
      - name: Install Python packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r requirements.txt black isort

      # Format code
      - name: Format code with Black
        run: black .

      - name: Sort imports with isort
        run: isort .
